Import('env')
from building import DefineGroup

kernel_root = Dir('#src/kernel').abspath
module_root = Dir('#src/modules').abspath
device_root = Dir('#src/modules/devices').abspath
platform_root = Dir('#src/platform').abspath

policy_env = env.Clone(BUILDERS={})
policy_env.Tool('cc')
policy_env.Replace(
    CFLAGS=env['CFLAGS'],
    CPPPATH=[kernel_root, module_root, device_root],
)
policy_env.Append(CCFLAGS=['-std=c11', '-Wall', '-Wextra', '-Werror'])
if GetOption('cdb'):
    policy_env.Tool('compilation_db')

service_group = DefineGroup(
    'IMU Service',
    ['imu_service.c'],
    depend=[''],
    CPPPATH=[kernel_root, module_root],
    LOCAL_CPPPATH=[device_root, platform_root],
    LOCAL_CCFLAGS=' -std=c11 -Wall -Wextra -Werror',
)
policy_objects = policy_env.Object(
    target='#build/firmware/kernel/imu/imu_policy',
    source='imu_policy.c',
)
policy_group = DefineGroup('IMU Policy', policy_objects, depend=[''])
group = service_group + policy_group

Return('group')
