Import('env', 'manifest')
from building import DefineGroup
from firmware_manifest import manifest_group_settings

module_root = Dir('#src/modules').abspath
settings = manifest_group_settings(manifest, 'modules', root=Dir('#').abspath)
telemetry_env = env.Clone(BUILDERS={})
telemetry_env.Tool('cc')
telemetry_env.Replace(
    CFLAGS=env['CFLAGS'],
    CPPPATH=settings['include_paths'],
    CPPDEFINES=settings['defines'],
)
telemetry_env.Append(CCFLAGS=['-std=c11', '-Wall', '-Wextra', '-Werror'])
if GetOption('cdb'):
    telemetry_env.Tool('compilation_db')

telemetry_objects = telemetry_env.Object(
    target='#build/scons/firmware/objects/modules/imu_telemetry/imu_telemetry',
    source='imu_telemetry.c',
)
telemetry_group = DefineGroup(
    'IMU Telemetry',
    telemetry_objects,
    depend=[],
    direct_dependencies=['Attitude'],
)

Return('telemetry_group')
