from building import *

cwd = GetCurrentDir()
module_root = Dir('#src/modules').abspath
device_root = Dir('#src/modules/devices').abspath
protocol_root = Dir('#src/modules/protocols').abspath
src = Glob('*.c')

group = DefineGroup('Applications', src, depend=[''],
                    CPPPATH=[cwd, module_root, device_root, protocol_root],
                    LOCAL_CCFLAGS=' -std=c11 -Wall -Wextra -Werror')

Return('group')
