from building import *

cwd = GetCurrentDir()
src = Glob('*.c')

group = DefineGroup('Applications', src, depend=[''], CPPPATH=[cwd],
                    LOCAL_CCFLAGS=' -std=c11 -Wall -Wextra -Werror')

Return('group')
