from building import *

cwd = GetCurrentDir()
kernel_root = Dir('#src/kernel').abspath
src = ['main.c']

group = DefineGroup('Applications', src, depend=[''],
                    CPPPATH=[cwd, kernel_root],
                    LOCAL_CCFLAGS=' -std=c11 -Wall -Wextra -Werror')

Return('group')
