Import('env')
from building import DefineGroup

module_root = Dir('#src/modules').abspath
transport_env = env.Clone(BUILDERS={})
transport_env.Tool('cc')
transport_env.Replace(CFLAGS=env['CFLAGS'], CPPPATH=[module_root])
transport_env.Append(CCFLAGS=['-std=c11', '-Wall', '-Wextra', '-Werror'])
if GetOption('cdb'):
    transport_env.Tool('compilation_db')

transport_objects = transport_env.Object(
    target='#build/firmware/modules/transport/dma_tx_state',
    source='dma_tx_state.c',
)
transport_group = DefineGroup('Transport', transport_objects, depend=[''])

Return('transport_group')
