import os


SConsignFile(os.path.join(os.getcwd(), 'build', 'scons', 'host-tests.dblite'))

base = Environment(
    CC='cc',
    CFLAGS=['-std=c11', '-O2', '-Wall', '-Wextra', '-Werror', '-pedantic'],
    LIBS=['m'],
)


def host_test(name, sources, include_paths):
    test_env = base.Clone()
    test_env.AppendUnique(CPPPATH=include_paths)
    objects = []
    for index, source in enumerate(sources):
        target = 'build/host-tests/obj/{}/{}'.format(name, index)
        objects.append(test_env.Object(target=target, source=source))
    return test_env.Program(
        target='build/host-tests/' + name,
        source=objects,
    )


module_include_paths = ['src/modules']
protocol_include_paths = ['src/modules/protocols'] + module_include_paths
device_include_paths = ['src/modules/devices'] + module_include_paths
bmi088_test_include_paths = ['tests/fakes'] + device_include_paths
imu_policy_include_paths = ['src/kernel'] + device_include_paths

test_timestamp_extender = host_test(
    'test_timestamp_extender',
    [
        'tests/modules/timing/test_timestamp_extender.c',
        'src/modules/timing/timestamp_extender.c',
    ],
    module_include_paths,
)
Alias('test_timestamp_extender', test_timestamp_extender)

test_bmi088 = host_test(
    'test_bmi088',
    [
        'tests/modules/devices/bmi088/test_bmi088.c',
        'tests/fakes/fake_bmi088_bus.c',
        'src/modules/devices/bmi088/bmi088.c',
    ],
    bmi088_test_include_paths,
)
Alias('test_bmi088', test_bmi088)

test_imu_telemetry = host_test(
    'test_imu_telemetry',
    [
        'tests/modules/protocols/imu_telemetry/test_imu_telemetry.c',
        'src/modules/protocols/imu_telemetry/imu_telemetry.c',
    ],
    protocol_include_paths,
)
Alias('test_imu_telemetry', test_imu_telemetry)

test_mahony = host_test(
    'test_mahony',
    [
        'tests/modules/attitude/test_mahony.c',
        'src/modules/attitude/mahony.c',
    ],
    module_include_paths,
)
Alias('test_mahony', test_mahony)

test_imu_calibration = host_test(
    'test_imu_calibration',
    [
        'tests/modules/attitude/test_imu_calibration.c',
        'src/modules/attitude/imu_calibration.c',
    ],
    module_include_paths,
)
Alias('test_imu_calibration', test_imu_calibration)

test_imu_policy = host_test(
    'test_imu_policy',
    [
        'tests/kernel/imu/test_imu_policy.c',
        'src/kernel/imu/imu_policy.c',
        'src/modules/attitude/imu_calibration.c',
        'src/modules/attitude/mahony.c',
    ],
    imu_policy_include_paths,
)
Alias('test_imu_policy', test_imu_policy)

test_telemetry_policy = host_test(
    'test_telemetry_policy',
    [
        'tests/kernel/telemetry/test_telemetry_policy.c',
        'src/kernel/telemetry/telemetry_policy.c',
    ],
    ['src/kernel'],
)
Alias('test_telemetry_policy', test_telemetry_policy)

test_dma_tx_state = host_test(
    'test_dma_tx_state',
    [
        'tests/modules/transport/test_dma_tx_state.c',
        'src/modules/transport/dma_tx_state.c',
    ],
    module_include_paths,
)
Alias('test_dma_tx_state', test_dma_tx_state)
