import os


SConsignFile(os.path.join(os.getcwd(), 'build', 'scons', 'host-tests.dblite'))

base = Environment(
    CC='cc',
    CFLAGS=['-std=c11', '-O2', '-Wall', '-Wextra', '-Werror', '-pedantic'],
    LIBS=['m'],
)


def host_test(name, sources, include_paths, defines=None, extra_objects=None):
    test_env = base.Clone()
    test_env.AppendUnique(CPPPATH=include_paths)
    if defines:
        test_env.AppendUnique(CPPDEFINES=defines)
    objects = list(extra_objects or [])
    for index, source in enumerate(sources):
        target = 'build/scons/host-tests/obj/{}/{}'.format(name, index)
        objects.append(test_env.Object(target=target, source=source))
    return test_env.Program(
        target='build/scons/host-tests/' + name,
        source=objects,
    )


module_include_paths = ['src/modules']
protocol_include_paths = ['src/modules/protocols'] + module_include_paths
device_include_paths = ['src/modules/devices'] + module_include_paths
bmi088_test_include_paths = ['tests/fakes'] + device_include_paths
imu_policy_include_paths = ['src/kernel'] + device_include_paths
imu_log_event_include_paths = [
    'src/kernel', 'src/modules/devices', 'src/modules'
]
logging_test_include_paths = [
    'tests/fakes', '.', 'src/kernel', 'src/modules', 'src/modules/devices'
]
logging_service_sources = [
    'src/kernel/logging/imu_log_service.c',
    'src/kernel/logging/imu_log_event.c',
    'tests/fakes/fake_rtthread_log.c',
]

test_timestamp_extender = host_test(
    'test_timestamp_extender',
    [
        'tests/modules/timing/test_timestamp_extender.c',
        'src/modules/timing/timestamp_extender.c',
    ],
    module_include_paths,
)
Alias('test_timestamp_extender', test_timestamp_extender)

test_bmi088 = host_test(
    'test_bmi088',
    [
        'tests/modules/devices/bmi088/test_bmi088.c',
        'tests/fakes/fake_bmi088_bus.c',
        'src/modules/devices/bmi088/bmi088.c',
    ],
    bmi088_test_include_paths,
)
Alias('test_bmi088', test_bmi088)

test_imu_telemetry = host_test(
    'test_imu_telemetry',
    [
        'tests/modules/protocols/imu_telemetry/test_imu_telemetry.c',
        'src/modules/protocols/imu_telemetry/imu_telemetry.c',
    ],
    protocol_include_paths,
)
Alias('test_imu_telemetry', test_imu_telemetry)

test_mahony = host_test(
    'test_mahony',
    [
        'tests/modules/attitude/test_mahony.c',
        'src/modules/attitude/mahony.c',
    ],
    module_include_paths,
)
Alias('test_mahony', test_mahony)

test_imu_calibration = host_test(
    'test_imu_calibration',
    [
        'tests/modules/attitude/test_imu_calibration.c',
        'src/modules/attitude/imu_calibration.c',
    ],
    module_include_paths,
)
Alias('test_imu_calibration', test_imu_calibration)

test_imu_policy = host_test(
    'test_imu_policy',
    [
        'tests/kernel/imu/test_imu_policy.c',
        'src/kernel/imu/imu_policy.c',
        'src/modules/attitude/imu_calibration.c',
        'src/modules/attitude/mahony.c',
    ],
    imu_policy_include_paths,
)
Alias('test_imu_policy', test_imu_policy)

test_service_lifecycle = host_test(
    'test_service_lifecycle',
    ['tests/kernel/test_service_lifecycle.c'],
    ['tests/fakes', 'src/kernel'],
)
Alias('test_service_lifecycle', test_service_lifecycle)

test_imu_log_event = host_test(
    'test_imu_log_event',
    [
        'tests/kernel/logging/test_imu_log_event.c',
        'src/kernel/logging/imu_log_event.c',
    ],
    imu_log_event_include_paths,
)
Alias('test_imu_log_event', test_imu_log_event)

test_imu_log_service = host_test(
    'test_imu_log_service',
    ['tests/kernel/logging/test_imu_log_service.c'] + logging_service_sources,
    logging_test_include_paths,
)
Alias('test_imu_log_service', test_imu_log_service)

test_imu_log_service_failure = host_test(
    'test_imu_log_service_failure',
    ['tests/kernel/logging/test_imu_log_service_failure.c'] + logging_service_sources,
    logging_test_include_paths,
)
Alias('test_imu_log_service_failure', test_imu_log_service_failure)

test_imu_log_service_startup_failure = host_test(
    'test_imu_log_service_startup_failure',
    ['tests/kernel/logging/test_imu_log_service_startup_failure.c']
    + logging_service_sources,
    logging_test_include_paths,
)
Alias('test_imu_log_service_startup_failure', test_imu_log_service_startup_failure)

test_imu_log_service_enabled = host_test(
    'test_imu_log_service_enabled',
    [
        'tests/kernel/logging/test_imu_log_service_enabled.c',
        'src/kernel/logging/imu_log_service.c',
        'src/kernel/logging/imu_log_event.c',
        'tests/fakes/fake_rtthread_log.c',
    ],
    [
        'tests/fakes/generated-debug-rtconfig', 'tests/fakes', '.',
        'src/kernel', 'src/modules', 'src/modules/devices'
    ],
)
Alias('test_imu_log_service_enabled', test_imu_log_service_enabled)

test_telemetry_policy = host_test(
    'test_telemetry_policy',
    [
        'tests/kernel/telemetry/test_telemetry_policy.c',
        'src/kernel/telemetry/telemetry_policy.c',
    ],
    ['src/kernel'],
)
Alias('test_telemetry_policy', test_telemetry_policy)

test_dma_tx_state = host_test(
    'test_dma_tx_state',
    [
        'tests/modules/transport/test_dma_tx_state.c',
        'src/modules/transport/dma_tx_state.c',
    ],
    module_include_paths,
)
Alias('test_dma_tx_state', test_dma_tx_state)

foxglove_uart_include_paths = ['tests/fakes', '.', 'src/platform', 'src/modules']
test_foxglove_debug_uart = host_test(
    'test_foxglove_debug_uart',
    [
        'tests/platform/transport/test_foxglove_debug_uart.c',
        'tests/fakes/fake_foxglove_uart_device.c',
        'src/platform/transport/foxglove_debug_uart_stm32.c',
    ],
    foxglove_uart_include_paths,
    ['HUOKONG_FOXGLOVE_DEBUG'],
)
Alias('test_foxglove_debug_uart', test_foxglove_debug_uart)

foxglove_debug_frame_env = base.Clone()
foxglove_debug_frame_env.AppendUnique(
    CPPPATH=[
        'tests/fakes/generated-debug-rtconfig',
        'src/debug', 'src/kernel', 'src/modules'
    ],
)
foxglove_debug_frame_object = foxglove_debug_frame_env.Object(
    target='build/scons/host-tests/obj/shared/foxglove_debug_frame',
    source='src/debug/foxglove_debug_frame.c',
)

test_foxglove_debug_frame = host_test(
    'test_foxglove_debug_frame',
    ['tests/debug/test_foxglove_debug_frame.c'],
    ['tests/fakes', 'src/debug', 'src/kernel', 'src/modules'],
    extra_objects=[foxglove_debug_frame_object],
)
Alias('test_foxglove_debug_frame', test_foxglove_debug_frame)

test_foxglove_debug_service = host_test(
    'test_foxglove_debug_service',
    [
        'tests/debug/test_foxglove_debug_service.c',
        'tests/fakes/fake_foxglove_debug_runtime.c',
        'src/debug/foxglove_debug.c',
    ],
    ['tests/fakes', '.', 'src/debug', 'src/kernel', 'src/modules', 'src/platform'],
    ['HUOKONG_FOXGLOVE_DEBUG'],
    extra_objects=[foxglove_debug_frame_object],
)
Alias('test_foxglove_debug_service', test_foxglove_debug_service)
