from building import *

module_root = Dir('#src/modules').abspath

timing_group = DefineGroup(
    'Timing',
    ['timestamp_extender.c'],
    depend=[''],
    CPPPATH=[module_root],
    LOCAL_CCFLAGS=' -std=c11 -Wall -Wextra -Werror',
)

Return('timing_group')
