import os
Import('env', 'manifest')
from building import *
from firmware_manifest import manifest_group_settings

cwd = GetCurrentDir()

# add general drivers
src = Split('''
board.c
CubeMX_Config/Src/stm32f1xx_hal_msp.c
''')


settings = manifest_group_settings(manifest, 'board', root=Dir('#').abspath)

group = DefineGroup(
    'Drivers',
    src,
    depend=[''],
    CPPPATH=settings['include_paths'],
    CPPDEFINES=settings['defines'],
)
Return('group')
