from building import *

cwd = GetCurrentDir()
root = Dir('#').abspath

driver_group = DefineGroup(
    'BMI088',
    ['bmi088.c', 'bmi088_port.c'],
    depend=[''],
    CPPPATH=[cwd, root],
    LOCAL_CCFLAGS=' -std=c11 -Wall -Wextra -Werror',
)

Return('driver_group')
