from building import *

cwd = GetCurrentDir()
root = Dir('#').abspath
module_root = Dir('#src/modules').abspath
device_root = Dir('#src/modules/devices').abspath

driver_group = DefineGroup(
    'BMI088 Port',
    ['bmi088_port.c'],
    depend=[''],
    CPPPATH=[cwd, root, module_root],
    LOCAL_CPPPATH=[device_root],
    LOCAL_CCFLAGS=' -std=c11 -Wall -Wextra -Werror',
)

Return('driver_group')
