from building import *

cwd = GetCurrentDir()
src = Glob('*.c')

group = DefineGroup(
    'Algorithm',
    src,
    depend=[''],
    CPPPATH=[cwd, Dir('#').abspath],
    LOCAL_CCFLAGS=' -std=c11 -Wall -Wextra -Werror',
)

Return('group')
