Import('env')
from building import DefineGroup

kernel_root = Dir('#src/kernel').abspath
module_root = Dir('#src/modules').abspath
protocol_root = Dir('#src/modules/protocols').abspath
platform_root = Dir('#src/platform').abspath

policy_env = env.Clone(BUILDERS={})
policy_env.Tool('cc')
policy_env.Replace(CFLAGS=env['CFLAGS'], CPPPATH=[kernel_root])
policy_env.Append(CCFLAGS=['-std=c11', '-Wall', '-Wextra', '-Werror'])
if GetOption('cdb'):
    policy_env.Tool('compilation_db')

service_group = DefineGroup(
    'Telemetry Service',
    ['telemetry_service.c'],
    depend=[''],
    CPPPATH=[kernel_root, module_root, protocol_root],
    LOCAL_CPPPATH=[platform_root],
    LOCAL_CCFLAGS=' -std=c11 -Wall -Wextra -Werror',
)
policy_objects = policy_env.Object(
    target='#build/firmware/kernel/telemetry/telemetry_policy',
    source='telemetry_policy.c',
)
policy_group = DefineGroup('Telemetry Policy', policy_objects, depend=[''])
group = service_group + policy_group

Return('group')
