Import('env', 'manifest')
from building import DefineGroup
from firmware_manifest import manifest_group_settings

module_root = Dir('#src/modules').abspath
settings = manifest_group_settings(manifest, 'platform', root=Dir('#').abspath)
clock_env = env.Clone(BUILDERS={})
clock_env.Tool('cc')
clock_env.Replace(
    CFLAGS=env['CFLAGS'],
    CPPPATH=settings['include_paths'],
    CPPDEFINES=settings['defines'],
)
clock_env.Append(CCFLAGS=['-std=c11', '-Wall', '-Wextra', '-Werror'])
if GetOption('cdb'):
    clock_env.Tool('compilation_db')

clock_objects = clock_env.Object(
    target='#build/scons/firmware/objects/platform/time/monotonic_clock_stm32',
    source='monotonic_clock_stm32.c',
)
clock_group = DefineGroup(
    'STM32 Monotonic Clock',
    clock_objects,
    depend=[],
    direct_dependencies=['Timing'],
)

Return('clock_group')
