Import('env', 'manifest')
from building import DefineGroup
from firmware_manifest import manifest_group_settings

platform_root = Dir('#src/platform').abspath
module_root = Dir('#src/modules').abspath
device_root = Dir('#src/modules/devices').abspath
settings = manifest_group_settings(manifest, 'platform', root=Dir('#').abspath)
device_env = env.Clone(BUILDERS={})
device_env.Tool('cc')
device_env.Replace(
    CFLAGS=env['CFLAGS'],
    CPPPATH=settings['include_paths'],
    CPPDEFINES=settings['defines'],
)
device_env.Append(CCFLAGS=['-std=c11', '-Wall', '-Wextra', '-Werror'])
if GetOption('cdb'):
    device_env.Tool('compilation_db')

device_objects = device_env.Object(
    target='#build/scons/firmware/objects/platform/devices/bmi088_stm32',
    source='bmi088_stm32.c',
)
device_group = DefineGroup('STM32 BMI088', device_objects, depend=[''])

Return('device_group')
